### ISSUE TITLE
Negative size showing for tags

### ISSUE THREAD

**Issue by nathanleclaire** [docker/hub-beta-feedback#112]
https://hub-beta.docker.com/r/nathanleclaire/serve/tags/

The tag for latest here shows -276.  Unless it gives me disk space on download, I don't think that's right :)

**Comment by rrarunan** [comment]
@nathanleclaire Its actually a `hyphen` https://github.com/docker/hub2-demo/blob/master/app/scripts/components/repo/repo_details/Tags.jsx#L45 that is part of the display. 
This is the in-progress version -> https://cloud.githubusercontent.com/assets/551247/8316150/f1794f96-19a9-11e5-9e9d-5d1aef38468d.png .. @ChristopherBiscardi is working on.

**Comment by cpuguy83** [comment]
Was just looking to see if an issue already existed for the overall layout of tags.
Is this still planned? Current one is really difficult to read in general due to lack of structure.

![screen shot 2015-08-03 at 3 13 04 pm](https://cloud.githubusercontent.com/assets/799078/9045605/5e1e2d3e-39f2-11e5-8033-5ced53a2ca5f.png)

**Comment by ChristopherBiscardi** [comment]
@cpuguy83 

The tags list was adjusted to be a table view in the interim while we work out a nicer way to visually compare tag sizes (of which the above screenshot is one possibility).

<img width="157" alt="screenshot 2015-08-04 09 48 48" src="https://cloud.githubusercontent.com/assets/551247/9066778/59bf9a56-3a8e-11e5-925b-b4dc89071c26.png">

**Comment by rrarunan** [comment]
I'm closing this, since the initial UX issue of showing `negative` image sizes isn't relevant anymore.
