### ISSUE TITLE
Linked Accounts & Services Status Incorrect

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#16]
Even after revoking the 'Docker Hub Registry' in github and relinking with Hub 2.0, the authorized services page (https://hub-beta.docker.com/account/authorized-services/) still displays "No Linked Account"

**Comment by rrarunan** [comment]
@kizbitz Can you go over the details on how you did the github relinking? Did you use `hub.docker.com` directly? Or did you follow the linking in the current hub-beta site. 

FYI, we are aware of an issue with linking github/bitbucket accounts with the `beta` site, since we cannot enable the production github app to work with the beta site.

**Comment by ChristopherBiscardi** [comment]
@rrarunan Has this been resolved by the new linking code?

**Comment by rrarunan** [comment]
Yes, the displaying of linked accounts correctly, is fixed on beta with the last deploy.
