### ISSUE TITLE
Github linking account doesn't work.

### ISSUE THREAD

**Issue by Meabed** [docker/hub-beta-feedback#289]
I try to link my github account to hub account but i always get redirected to the site with url 
https://hub.docker.com/account/authorized-services/github/?code=XXXXXXXXX&state=XXXXX
but it never works.. I have this github account linked to another hub account before so it might be the issue.

**Comment by rrarunan** [comment]
@Meabed Yes, that is indeed the issue. We are working on a better error message for this scenario of multiple hub accounts for the same github account.

**Comment by Meabed** [comment]
@rrarunan and if i want to have my account linked to multiple dockers ( one personal ) and on for the company i work for as an example? how can i do this ?

**Comment by rrarunan** [comment]
@Meabed  So, if the company you work for, is a `docker hub organization`.. You can still create repositories in that organization's namespace (provided you are in the `owners` team that is created by default). Does that answer your question?

**Comment by rrarunan** [comment]
deployed a fix to inform users of failures during linking.

**Comment by dnephin** [comment]
I guess I'm hitting this as well.

I'd like to use automated builds for my github account, but I links failed, I guess because I'm part of the docker organization on the hub?

I could push to the docker account on the hub I guess, but I don't really want to do that for projects that aren't directly related to docker.

Is there an issue I can follow for supporting this?
