### ISSUE TITLE
Dollar signs don't line up in PRE-formatted Markdown description

### ISSUE THREAD

**Issue by mcandre** [docker/hub-beta-feedback#323]
I entered a fairly typical Markdown PRE-formatted code snippet, a command line trace, into my DockerHub description, but DockerHub's Markdown renderer somehow fails at displaying it properly.

https://hub.docker.com/r/mcandre/docker-pxe/

Why don't those dollar signs line up?

**Comment by ChristopherBiscardi** [comment]
This issue is currently covered in #124 under code blocks. (so I'm going to close this specific ticket in favor of the other one)

Mainly, we aren't getting the right results from non-language specified code blocks. 

The top example in the screenshot is using:

> &#96;&#96;&#96;bash

the bottom is using 

> &#96;&#96;&#96;


<img width="781" alt="screenshot 2015-09-02 11 27 13" src="https://cloud.githubusercontent.com/assets/551247/9640287/c53e829a-5165-11e5-93eb-ca80051db235.png">
