### ISSUE TITLE
Assign official images to upstream organisations

### ISSUE THREAD

**Issue by Djelibeybi** [docker/hub-beta-feedback#53]
It would be great if the new Hub allowed an organisation to assume ownership of an official image. That way, end-users can determine who is providing the image itself and make decisions based on that knowledge. 

For example, currently there is no way to know that Oracle is actually providing the Oracle Linux images but is NOT providing the MySQL or Glassfish images.

**Comment by toli** [comment]
@Djelibeybi , i'm not sure that I follow. 
we do have an `Official Images` user on Hub which owns various images.
So the Official MySQL image is at https://registry.hub.docker.com/_/mysql/
while Oracle Linux is at https://registry.hub.docker.com/_/oraclelinux/

For official images, we try to have them all be owned by "library" user, and then we will of course love to have others/upstream maintainers so that we can share the work.

Are you suggesting that we should have a way to "promote" an image to be Official? or allowing User-1 to assume ownership of Project-A from User-2?

Could you clarify? Perhaps we need to make the "official images" user more prominent?

**Comment by Djelibeybi** [comment]
The Official Images user hides the source of the official image itself. For example, the official MySQL image is not provided by MySQL. And the official Glassfish image is not provided by the Glassfish team.

There should be a way to clearly identify the upstream sponsor/source of an official image, instead of having them all masked by the "library" user in the Hub. Thus, end-users can see that the official MySQL image is actually provided by Docker (not Oracle) and that the official Glassfish image is provided by Amazon (not Oracle).

Having an image labeled as official implies a level of testing and integration for the product which may not actually be the case. It also implies that the vendor of the product would support the image which may also not be the case.

Does that make it clearer?

**Comment by ChristopherBiscardi** [comment]
Thanks for the feedback; We are looking into ways to enhance the usability of the Official Images both on the Hub and elsewhere. We would love to get your feedback and the product team will reach out to you shortly.
