### ISSUE TITLE
'Organizations' link in secondary menu under user account settings is unnecessary

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#67]
There is already an 'Organizations' menu link in the top main nav bar. The secondary one could be removed. (From the gear icon in upper right)

![screen shot 2015-06-16 at 8 30 56 am](https://cloud.githubusercontent.com/assets/201920/8182953/5c5d1d36-1402-11e5-82c3-43ffe941a8b8.png)

**Comment by ChristopherBiscardi** [comment]
After discussing with @rrarunan we're going to close this as `wontfix` since both links have reasonable explanations for where they are even though it looks a bit weird to have them so close to each other. Ultimately, we (currently) want people going to the Dashboard as the entrypoint to action. Since the Organizations Dashboard has Teams, Repos, etc. the anticipation is that people will eventually not need the `Organizations` top-level object. We can revisit this after the transitionary period between Hub 1 and Hub 2 happens and we can evaluate more accurately how people are using the site.
