### ISSUE TITLE
Cannot create repos for orgs

### ISSUE THREAD

**Issue by ewindisch** [docker/hub-beta-feedback#78]
Creating a new repo for an org fails.

![screen shot 2015-06-16 at 3 32 36 pm](https://cloud.githubusercontent.com/assets/73207/8192595/49f1a276-143d-11e5-934e-7118ffcb9d3a.png)

**Comment by ChristopherBiscardi** [comment]
Bad Request means there's something wrong with the input (You can check the response body to confirm). Likely, this is because you have no more private repositories on the `apple3` account. We are working to get this feedback back into the form after a recent change to the way the form feedback is handled.

**Comment by rrarunan** [comment]
Deployed the private repos message.
