### ISSUE TITLE
'Organization Username' should be removed from the Create Organization form

### ISSUE THREAD

**Issue by kizbitz** [docker/hub-beta-feedback#9]
Once https://github.com/docker/hub-beta-feedback/issues/8 is taken care of...

Having a 'Username' field is not necessary. 
![screen shot 2015-06-04 at 10 38 17 am](https://cloud.githubusercontent.com/assets/201920/7986560/413f2388-0aa6-11e5-98a5-6b0f0424065a.png)

Currently no matter what you enter as a user (Existing hub account, Non-existing hub account, or leave blank) the result is always the same. > The org gets created with the currently logged in user in the 'owner' team/group.

**Comment by rrarunan** [comment]
@fxdgear @kencochrane @ChristopherBiscardi The Organization Name being the Organization's full_name and the Organization Username being `Organization Namespace`, is fine? I believe we can't remove that field. I think @kizbitz believes it to be the current username because of the current wording.. but its actually the unique org namespace.

**Comment by ChristopherBiscardi** [comment]
Closing this to consolidate the conversation on #8
